export const EVENT_TYPE = Object.freeze({
    UPDATE_ELEMENT: 'update-element',
    UPDATE_NAVIGATION_PATH: 'update-navigation-path',
    GENERATE_DIAGRAM: 'generate-diagram',
    CLEAR_DIAGRAM: 'clear-diagram',
    SAVE_DIAGRAM: 'save-diagram',
    LOAD_FILE: 'load-file',
    LOAD_FILE_SUCCESS: 'load-file-success',
    LOAD_FILE_ERROR: 'load-file-error',
    CLEAR_FILE: 'clear-file',
    SET_API_KEY: 'set-api-key',
    API_KEY_LOADED: 'api-key-loaded',
    API_KEY_SAVED: 'api-key-saved',
    API_KEY_CLEARED: 'api-key-cleared',
    LOAD_DIAGRAMS_FROM_SYSTEM: 'load-diagrams-from-system',
    LOAD_DIAGRAM_FROM_SYSTEM: 'load-diagram-from-system',
    SHOW_DIAGRAMS_FROM_SYSTEM: 'show-diagrams-from-system',
    OPEN_MODAL: 'open-modal',
    CLOSE_MODAL: 'close-modal',
    MODAL_CLOSED: 'modal-closed',
    CREATE_LISTENER: 'create-listener',
    EDIT_LISTENER: 'edit-listener',
    REMOVE_LISTENER: 'remove-listener',
    SAVE_LISTENER: 'save-listener',
    ADD_CREATED_LISTENER: 'add-create-listener',
    UPDATE_EDITED_LISTENER: 'update-edited-listener',
    CREATE_LISTENER_FIELD: 'create-listener-field',
    EDIT_LISTENER_FIELD: 'edit-listener-field',
    REMOVE_LISTENER_FIELD: 'remove-listener-field',
    ADD_CREATED_LISTENER_FIELD: 'add-create-listener-field',
    TASK_TYPES_READY: 'task-types-ready',
    GATEWAY_TYPES_READY: 'gateway-types-ready',
    JAVA_CLASSES_LISTING_READY: 'java-classes-listing-ready',
    CREATE_FORM_PROPERTY: 'create-form-property',
    EDIT_FORM_PROPERTY: 'edit-form-property',
    ADD_CREATED_FORM_PROPERTY: 'add-created-form-property',
    SAVE_FORM_PROPERTY: 'save-form-property',
    UPDATE_EDITED_FORM_PROPERTY: 'update-edited-form-property'
});


