export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
export const RESOURCE_PUBLISH_ENDPOINT = import.meta.env.VITE_API_RESOURCE_PUBLISH_ENDPOINT;
export const API_RESOURCE_PUBLISH_URL = `${API_BASE_URL}${RESOURCE_PUBLISH_ENDPOINT}`;
