name: Build and Test

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [20.x, 21.x, 22.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
  test:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [20.x, 21.x, 22.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test   

      - name: Test coverage
        run: npm run test:cov
